apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
  - github.com/redhat-cop/gitops-catalog/openshift-pipelines-tasks/rollout-restart/base?ref=v0.3
  - github.com/redhat-cop/gitops-catalog/openshift-pipelines-tasks/maven/base?ref=v0.3
  - github.com/redhat-cop/gitops-catalog/openshift-pipelines-tasks/s2i-binary-build/base?ref=v0.3

resources:
  - 01-workspace-pvc.yaml
  - 02-build-and-rollout-pipeline.yaml