kind: Application
apiVersion: argoproj.io/v1alpha1
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "2"
  name: cicd-tools
spec:
  destination:
    namespace: cicd-tools
    server: https://kubernetes.default.svc
  project: petclinic-projects-project
  source:
    path: 01-projects/cicd
    repoURL: https://github.com/pittar-gitops/gitops-mono-repo-petclinic.git
    targetRevision: main
  syncPolicy:
    automated:
      prune: false
      selfHeal: true