apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonAnnotations:
  argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
  argocd.argoproj.io/sync-wave: "2"

bases:
  - github.com/redhat-cop/gitops-catalog/openshift-pipelines-tasks/rollout-restart/base?ref=v0.3
  - github.com/redhat-cop/gitops-catalog/openshift-pipelines-tasks/maven/base?ref=v0.3
  - github.com/redhat-cop/gitops-catalog/openshift-pipelines-tasks/s2i-binary-build/base?ref=v0.3

resources:
  - https://raw.githubusercontent.com/gnunn1/contributions/main/ci/Tekton/Tasks/rox-image-check-task.yml
  - https://raw.githubusercontent.com/stackrox/contributions/main/ci/Tekton/Tasks/rox-image-scan-task.yml
  - 01-workspace-pvc.yaml
  - 02-build-and-rollout-pipeline.yaml
