kind: Application
apiVersion: argoproj.io/v1alpha1
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "2"
  name: petclinic-cicd
spec:
  destination:
    namespace: petclinic-cicd
    server: https://kubernetes.default.svc
  project: devteam1-projects-project
  source:
    path: 01-projects/petclinic/cicd
    repoURL: https://github.com/pittar-gitops/gitops-mono-repo-devteam1.git
    targetRevision: main
  syncPolicy:
    automated:
      prune: false
      selfHeal: true