kind: Kustomization
apiVersion: kustomize.config.k8s.io/v1beta1

namespace: developer-gitops

bases:
  # List of Projects for this tenant in this cluster.
  - ../../../02-namespaces/petclinic-cicd
  - ../../../02-namespaces/petclinic-dev
  - ../../../02-namespaces/petclinic-test

resources:
  - projects-project.yaml