apiVersion: v1
kind: Secret
metadata:
  labels:
    app: nexus
  name: nexus-secret
stringData:
  MAVEN_SERVER_USERNAME: admin
  MAVEN_SERVER_PASSWORD: admin123
  MAVEN_SERVER_HOST: http://nexus.devteam1-cicd.svc.cluster.local:8081
  SONAR_SERVER_HOST: http://sonarqube.devteam1-cicd.svc.cluster.local:9000