apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Deploy pre-configured SonarQube and Nexus from Red Hat Canada demo catalog.
bases:
  - github.com/redhat-cop/gitops-catalog/nexus2/base?ref=v0.3
  - github.com/redhat-cop/gitops-catalog/sonarqube8/overlays/plugins?ref=v0.3